services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - appnet

  # PRODUCERS
  producer-python:
    build: ../../services/producers/python
    depends_on: [rabbitmq]
    networks: [appnet]
    command: ["sh", "-c", "/scripts/wait-for-rabbit.sh rabbitmq python producer.py"]
    volumes:
      - ../../scripts:/scripts:ro

  producer-node:
    build: ../../services/producers/nodejs
    depends_on: [rabbitmq]
    networks: [appnet]
    command: ["sh", "-c", "/scripts/wait-for-rabbit.sh rabbitmq node app.js"]
    volumes:
      - ../../scripts:/scripts:ro

  producer-java:
    build: ../../services/producers/java
    depends_on: [rabbitmq]
    networks: [appnet]
    command: ["sh", "-c", "/scripts/wait-for-rabbit.sh rabbitmq java -cp out:lib/* com.example.producer.Producer"]
    volumes:
      - ../../scripts:/scripts:ro

  producer-go:
    build: ../../services/producers/go
    depends_on: [rabbitmq]
    networks: [appnet]
    command: ["sh", "-c", "/scripts/wait-for-rabbit.sh rabbitmq ./main"]
    volumes:
      - ../../scripts:/scripts:ro

  # CONSUMERS
  consumer-python:
    build: ../../services/consumers/python
    depends_on: [rabbitmq]
    networks: [appnet]
    command: ["sh", "-c", "/scripts/wait-for-rabbit.sh rabbitmq python consumer.py"]
    volumes:
      - ../../scripts:/scripts:ro

  consumer-node:
    build: ../../services/consumers/nodejs
    depends_on: [rabbitmq]
    networks: [appnet]
    command: ["sh", "-c", "/scripts/wait-for-rabbit.sh rabbitmq node app.js"]
    volumes:
      - ../../scripts:/scripts:ro

  consumer-java:
    build: ../../services/consumers/java
    depends_on: [rabbitmq]
    networks: [appnet]
    command: ["sh", "-c", "/scripts/wait-for-rabbit.sh rabbitmq java -cp out:lib/* com.example.consumer.Consumer"]
    volumes:
      - ../../scripts:/scripts:ro

  consumer-go:
    build: ../../services/consumers/go
    depends_on: [rabbitmq]
    networks: [appnet]
    command: ["sh", "-c", "/scripts/wait-for-rabbit.sh rabbitmq ./main"]
    volumes:
      - ../../scripts:/scripts:ro

networks:
  appnet:
