services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PRODUCERS
  producer-python:
    build: ../../services/producers/python
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks: [appnet]
    command: >
      sh -c "
        until nc -z rabbitmq 5672; do
          echo 'Waiting for RabbitMQ...';
          sleep 3;
        done;
        echo 'RabbitMQ is ready!';
        python producer.py
      "

  producer-node:
    build: ../../services/producers/nodejs
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks: [appnet]
    command: >
      sh -c "
        until nc -z rabbitmq 5672; do
          echo 'Waiting for RabbitMQ...';
          sleep 3;
        done;
        echo 'RabbitMQ is ready!';
        node app.js
      "

  producer-java:
    build: ../../services/producers/java
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks: [appnet]
    command: >
      sh -c "
        until nc -z rabbitmq 5672; do
          echo 'Waiting for RabbitMQ...';
          sleep 3;
        done;
        echo 'RabbitMQ is ready!';
        java -cp out:lib/* com.example.producer.Producer
      "

  producer-go:
    build: ../../services/producers/go
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks: [appnet]
    command: >
      sh -c "
        until nc -z rabbitmq 5672; do
          echo 'Waiting for RabbitMQ...';
          sleep 3;
        done;
        echo 'RabbitMQ is ready!';
        ./main
      "

  # CONSUMERS
  consumer-python:
    build: ../../services/consumers/python
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks: [appnet]
    command: >
      sh -c "
        until nc -z rabbitmq 5672; do
          echo 'Waiting for RabbitMQ...';
          sleep 3;
        done;
        echo 'RabbitMQ is ready!';
        python consumer.py
      "

  consumer-node:
    build: ../../services/consumers/nodejs
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks: [appnet]
    command: >
      sh -c "
        until nc -z rabbitmq 5672; do
          echo 'Waiting for RabbitMQ...';
          sleep 3;
        done;
        echo 'RabbitMQ is ready!';
        node app.js
      "

  consumer-java:
    build: ../../services/consumers/java
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks: [appnet]
    command: >
      sh -c "
        until nc -z rabbitmq 5672; do
          echo 'Waiting for RabbitMQ...';
          sleep 3;
        done;
        echo 'RabbitMQ is ready!';
        java -cp out:lib/* com.example.consumer.Consumer
      "

  consumer-go:
    build: ../../services/consumers/go
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks: [appnet]
    command: >
      sh -c "
        until nc -z rabbitmq 5672; do
          echo 'Waiting for RabbitMQ...';
          sleep 3;
        done;
        echo 'RabbitMQ is ready!';
        ./main
      "

networks:
  appnet: