services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - appnet

  # PRODUCERS
  producer-node:
    build: ../../services/producers/nodejs
    depends_on: [rabbitmq]
    networks: [appnet]
    command: >
      sh -c "
        until nc -z rabbitmq 5672; do
          echo 'Waiting for RabbitMQ...';
          sleep 3;
        done;
        echo 'RabbitMQ is ready!';
        node app.js
      "
    volumes:
      - ../../scripts:/scripts:ro

  producer-node2:
    build: ../../services/producers/nodejs2
    depends_on: [rabbitmq]
    networks: [appnet]
    command: >
      sh -c "
        until nc -z rabbitmq 5672; do
          echo 'Waiting for RabbitMQ...';
          sleep 3;
        done;
        echo 'RabbitMQ is ready!';
        node app.js
      "
    volumes:
      - ../../scripts:/scripts:ro

  producer-java:
    build: ../../services/producers/java
    depends_on: [rabbitmq]
    networks: [appnet]
    command: >
      sh -c "
        until nc -z rabbitmq 5672; do
          echo 'Waiting for RabbitMQ...';
          sleep 3;
        done;
        echo 'RabbitMQ is ready!';
        java -cp out:lib/* com.example.producer.Producer
      "
    volumes:
      - ../../scripts:/scripts:ro

  producer-go:
    build: ../../services/producers/go
    depends_on: [rabbitmq]
    networks: [appnet]
    command: >
      sh -c "
        until nc -z rabbitmq 5672; do
          echo 'Waiting for RabbitMQ...';
          sleep 3;
        done;
        echo 'RabbitMQ is ready!';
        ./main
      "
    volumes:
      - ../../scripts:/scripts:ro

  # CONSUMERS
  consumer-node:
    build: ../../services/consumers/nodejs
    depends_on: [rabbitmq]
    networks: [appnet]
    command: >
      sh -c "
        until nc -z rabbitmq 5672; do
          echo 'Waiting for RabbitMQ...';
          sleep 3;
        done;
        echo 'RabbitMQ is ready!';
        node app.js
      "
    volumes:
      - ../../scripts:/scripts:ro

  consumer-node2:
    build: ../../services/consumers/nodejs2
    depends_on: [rabbitmq]
    networks: [appnet]
    command: >
      sh -c "
        until nc -z rabbitmq 5672; do
          echo 'Waiting for RabbitMQ...';
          sleep 3;
        done;
        echo 'RabbitMQ is ready!';
        node app.js
      "
    volumes:
      - ../../scripts:/scripts:ro

  consumer-java:
    build: ../../services/consumers/java
    depends_on: [rabbitmq]
    networks: [appnet]
    command: >
      sh -c "
        until nc -z rabbitmq 5672; do
          echo 'Waiting for RabbitMQ...';
          sleep 3;
        done;
        echo 'RabbitMQ is ready!';
        java -cp out:lib/* com.example.consumer.Consumer
      "
    volumes:
      - ../../scripts:/scripts:ro

  consumer-go:
    build: ../../services/consumers/go
    depends_on: [rabbitmq]
    networks: [appnet]
    command: >
      sh -c "
        until nc -z rabbitmq 5672; do
          echo 'Waiting for RabbitMQ...';
          sleep 3;
        done;
        echo 'RabbitMQ is ready!';
        ./main
      "
    volumes:
      - ../../scripts:/scripts:ro

networks:
  appnet:
